apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: banking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "joao"
            - name: POSTGRES_PASSWORD
              value: "joao"
            - name: POSTGRES_DB
              value: "agencia"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-scripts
      volumes:
        - name: postgres-storage
          emptyDir: {}
        - name: init-scripts
          configMap:
            name: postgres-init-scripts